apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ttypdb-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - delete
