name: "Build Cilium Agent"
description: "Building cilium-agent"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  yamory_token:
    description: "Yamory Access Token"
    required: true
  cilium-proxy_version:
    description: "cilium/proxy(envoy) version"
    required: true
  image-tools_version:
    description: "cilium/image-tools version"
    required: true
runs:
  using: composite
  steps:
    - name: Setup build environment
      uses: ./.github/actions/setup
      with:
        github_token: ${{ inputs.github_token }}

    - id: prepare
      name: Prepare build parameters
      uses: ./.github/actions/prepare_build_params
      with:
        dir: ./cilium
        container-image: cilium
        github_token: ${{ inputs.github_token }}
        request-scan: "true"

    - name: Build Cilium image tools
      if: ${{ steps.prepare.outputs.build }}
      uses: ./.github/actions/build_cilium-image-tools
      with:
        github_token: ${{ inputs.github_token }}
        image-tools_version: ${{ inputs.image-tools_version }}

    - name: Download artifacts of cilium-envoy
      if: ${{ steps.prepare.outputs.build }}
      uses: actions/download-artifact@v4
      with:
        name: cilium-envoy
        path: cilium/src/workspace

    - name: Untar cilium-envoy
      if: ${{ steps.prepare.outputs.build }}
      shell: bash
      run: |
        cd cilium/src/workspace
        tar -xvf cilium-envoy.tar

    - name: Build cilium-agent image and push
      if: ${{ steps.prepare.outputs.build }}
      uses: docker/build-push-action@v5
      with:
        context: cilium
        platforms: "linux/amd64"
        provenance: false
        push: ${{ steps.prepare.outputs.docker_push }}
        tags: |
          ${{ steps.prepare.outputs.tag }}
          ${{ steps.prepare.outputs.branch }}

    - name: Scan images
      if: ${{ steps.prepare.outputs.scan }}
      uses: ./.github/actions/trivy_scan
      with:
        dir: ./cilium
        container-image: cilium
        tag: ${{ steps.prepare.outputs.tag }}
        yamory_token: ${{ inputs.yamory_token }}
