name: "Build Cilium Agent"
description: "Building cilium-agent"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  yamory_token:
    description: "Yamory Access Token"
    required: true
  cilium-proxy_version:
    description: "cilium/proxy(envoy) version"
    required: true
  image-tools_version:
    description: "cilium/image-tools version"
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64/v8

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - id: extract
      name: Extract targets
      uses: ./.github/actions/extract_tags
      with:
        dir: ./cilium
        container-image: cilium
        github_token: ${{ inputs.github_token }}
        request-scan: "true"

    - name: Build Cilium Envoy
      uses: ./.github/actions/build_cilium-envoy
      with:
        github_token: ${{ inputs.github_token }}
        cilium-proxy_version: ${{ inputs.cilium-proxy_version }}

    - name: Build Cilium image tools
      uses: ./.github/actions/build_cilium-image-tools
      with:
        github_token: ${{ inputs.github_token }}
        image-tools_version: ${{ inputs.image-tools_version }}

    - name: Build cilium-agent image and push
      if: ${{ steps.extract.outputs.build }}
      uses: docker/build-push-action@v5
      with:
        context: cilium
        platforms: "linux/amd64"
        provenance: false
        push: ${{ steps.extract.outputs.docker_push }}
        tags: |
          ${{ steps.extract.outputs.tag }}
          ${{ steps.extract.outputs.branch }}

    - name: Install Trivy
      if: ${{ inputs.scan == 'true' && steps.extract.outputs.push }}
      shell: bash
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan the image
      if: ${{ inputs.scan == 'true' && steps.extract.outputs.push }}
      shell: bash
      env:
        YAMORY_ACCESS_TOKEN: ${{ inputs.yamory_token }}
      run: |
        echo
        echo "scanning ${{ steps.extract.outputs.tag }} ..."
        if [[ "${{ steps.extract.outputs.tag }}" == "ghcr.io/cybozu/golang:"* ]]; then
          dir=./cilium
          BRANCH=$(cat $dir/BRANCH)
          image=cilium:$BRANCH
        else
          image=cilium
        fi
        YAMORY_IMAGE_IDENTIFIER="ghcr.io/cybozu/$image" YAMORY_IMAGE_NAME="${{ steps.extract.outputs.tag }}" bash -c "$(curl -sSf -L https://mw-receiver.yamory.io/image/script/trivy)"
