name: "Build Cilium Agent"
description: "Building cilium-agent"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  yamory_token:
    description: "Yamory Access Token"
    required: true
  cilium-proxy_version:
    description: "cilium/proxy(envoy) version"
    required: true
  image-tools_version:
    description: "cilium/image-tools version"
    required: true
runs:
  using: composite
  steps:
    - name: Setup build environment
      uses: ./.github/actions/setup
      with:
        github_token: ${{ inputs.github_token }}

    - id: extract
      name: Extract targets
      uses: ./.github/actions/extract_tags
      with:
        dir: ./cilium
        container-image: cilium
        github_token: ${{ inputs.github_token }}
        request-scan: "true"

    - name: Build Cilium Envoy
      uses: ./.github/actions/build_cilium-envoy
      with:
        github_token: ${{ inputs.github_token }}
        cilium-proxy_version: ${{ inputs.cilium-proxy_version }}

    - name: Build Cilium image tools
      uses: ./.github/actions/build_cilium-image-tools
      with:
        github_token: ${{ inputs.github_token }}
        image-tools_version: ${{ inputs.image-tools_version }}

    - name: Build cilium-agent image and push
      if: ${{ steps.extract.outputs.build }}
      uses: docker/build-push-action@v5
      with:
        context: cilium
        platforms: "linux/amd64"
        provenance: false
        push: ${{ steps.extract.outputs.docker_push }}
        tags: |
          ${{ steps.extract.outputs.tag }}
          ${{ steps.extract.outputs.branch }}

    - name: Scan images
      if: ${{ steps.extract.outputs.scan }}
      uses: ./.github/actions/trivy_scan
      with:
        dir: ./cilium
        container-image: cilium
        tag: ${{ steps.extract.outputs.tag }}
        yamory_token: ${{ inputs.yamory_token }}
