name: "Build Cilium Envoy"
description: "Build Cilium Envoy"
inputs:
  cilium-proxy_version:
    description: "cilium-proxy(envoy) version"
    required: true
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ca-certificates \
          autoconf \
          automake \
          cmake \
          coreutils \
          curl \
          git \
          libtool \
          make \
          ninja-build \
          patch \
          patchelf \
          python3 \
          python-is-python3 \
          unzip \
          virtualenv \
          wget \
          zip \
          software-properties-common
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        sudo apt-add-repository -y "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main"
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          clang-17 clang-tools-17 llvm-17-dev lldb-17 lld-17 clang-format-17 libc++-17-dev libc++abi-17-dev

    - name: Download cilium/proxy
      shell: bash
      run: |
        mkdir -p cilium/src/workspace/usr/bin cilium/src/cilium-proxy
        curl -sSLf https://github.com/cilium/proxy/archive/${{ inputs.cilium-proxy_version }}.tar.gz | \
          tar zxf - --strip-components 1 -C cilium/src/cilium-proxy

    - name: Build libcilium.so
      shell: bash
      run: |
        mkdir -p cilium/src/workspace/usr/lib
        cd cilium/src/cilium-proxy
        make -C proxylib all && mv proxylib/libcilium.so ../workspace/usr/lib

    - name: Build cilium-envoy
      shell: bash
      env:
        BAZEL_BUILD_OPTS: "--remote_upload_local_results=false --disk_cache=/tmp/bazel-cache --verbose_failures"
        PKG_BUILD: 1
        DESTDIR: /tmp/install
      run: |
        rm -rf cilium/proxy/.cache/*
        export PKG_BUILD=${{ env.PKG_BUILD }}
        export DESTDIR=${{ env.DESTDIR }}
        cd cilium/src/cilium-proxy
        echo ${{ inputs.cilium-proxy_version }} > SOURCE_VERSION
        make bazel-bin/cilium-envoy-starter bazel-bin/cilium-envoy BAZEL_BUILD_OPTS="${{ env.BAZEL_BUILD_OPTS }}"
        ./bazel/get_workspace_status
        make install
        sudo mv /tmp/install/usr/bin/cilium-envoy ../workspace/usr/bin/
        sudo mv /tmp/install/usr/bin/cilium-envoy-starter ../workspace/usr/bin/

