name: "Build Cilium Envoy"
description: "Build Cilium Envoy"
inputs:
  cilium-proxy_version:
    description: "cilium-proxy(envoy) version"
    required: true
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ca-certificates \
          autoconf \
          automake \
          cmake \
          coreutils \
          curl \
          git \
          libtool \
          make \
          ninja-build \
          patch \
          patchelf \
          python3 \
          python-is-python3 \
          unzip \
          virtualenv \
          wget \
          zip
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        sudo bash -c 'echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" >> /etc/apt/sources.list'
        sudo bash -c 'echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main" >> /etc/apt/sources.list'
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          clang-15 \
          clang-tools-15 \
          lldb-15 \
          lld-15 \
          clang-format-15 \
          libc++-15-dev \
          libc++abi-15-dev

    - name: Download cilium/proxy
      shell: bash
      run: |
        mkdir -p cilium/src/workspace/usr/bin cilium/src/cilium-proxy
        curl -sSLf https://github.com/cilium/proxy/archive/${{ inputs.cilium-proxy_version }}.tar.gz | \
          tar zxf - --strip-components 1 -C cilium/src/cilium-proxy

    - name: Build cilium-envoy
      shell: bash
      env:
        BAZEL_BUILD_OPTS: "--remote_upload_local_results=false --disk_cache=/tmp/bazel-cache --verbose_failures"
        PKG_BUILD: 1
        DESTDIR: /tmp/install
      run: |
        export PKG_BUILD=${{ env.PKG_BUILD }}
        export DESTDIR=${{ env.DESTDIR }}
        cd cilium/src/cilium-proxy
        echo ${{ inputs.cilium-proxy_version }} > SOURCE_VERSION
        make bazel-bin/cilium-envoy BAZEL_BUILD_OPTS="${{ env.BAZEL_BUILD_OPTS }}"
        ./bazel/get_workspace_status
        make install
        sudo mv /tmp/install/usr/bin/cilium-envoy ../workspace/usr/bin/
