name: "Build ceph"
description: "Build ceph"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  version:
    description: "ceph version"
    required: true
runs:
  using: composite
  steps:
    - name: Setup build environment
      uses: ./.github/actions/setup
      with:
        github_token: ${{ inputs.github_token }}
    - id: prepare
      name: Prepare build parameters
      uses: ./.github/actions/prepare_build_params
      with:
        container-image: ceph
        github_token: ${{ inputs.github_token }}
    - name: Build
      if: ${{ steps.prepare.outputs.build }}
      shell: bash
      run: |
        sudo ./build.sh ${{ inputs.version }}
        sudo mv src/workspace .
      working-directory: ceph
    - name: Build and push
      if: ${{ steps.prepare.outputs.build }}
      uses: docker/build-push-action@v6
      with:
        context: ceph
        platforms: "linux/amd64"
        provenance: false
        push: ${{ steps.prepare.outputs.docker_push }}
        tags: |
          ${{ steps.prepare.outputs.tag }}
          ${{ steps.prepare.outputs.branch }}
