name: "Prepare build matrix"
description: "Prepare build matrix"
inputs:
  matrix:
    description: "Candidate build jobs"
    required: true
    default: ""
outputs:
  jobs:
    description: "matrix"
    value: ${{ steps.prepare-matrix.outputs.jobs }}

runs:
  using: composite
  steps:
    - name: Check and output changed files
      id: changed-files
      uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7
      with:
        files_ignore: |
          **/*.md
        separator: ','
        write_output_files: 'true'
    - id: prepare-matrix
      shell: bash
      env:
        INPUT_MATRIX: ${{ inputs.matrix }}
      run: |
        ./generate_matrix
        echo "jobs=$(cat .github/outputs/__matrix.json)" >> $GITHUB_OUTPUT
