name: main
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build_container:
    strategy:
      matrix:
        job:
          - dir: ./golang-all/golang-1.19-focal
            container-image: "golang"
            enable_arm64: true
          - dir: ./golang-all/golang-1.19-jammy
            container-image: "golang"
            enable_arm64: true
          - dir: "./golang-all/golang-1.20-focal"
            container-image: "golang"
            enable_arm64: true
          - dir: "./golang-all/golang-1.20-jammy"
            container-image: "golang" 
            enable_arm64: true
          - dir: "./haproxy"
            container-image: "haproxy"
          - dir: "./kube-summary-exporter"
            container-image: "kube-summary-exporter"
          - dir: "./trust-manager"
            container-image: "trust-manager"

    runs-on: ubuntu-22.04
    env:
      go-version: "1.19"
    steps:
      - uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go-version: ${{ env.go-version }}
      - name: Build container image
        uses: ./.github/actions/build_push
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dir: ${{ matrix.job.dir }}
          container-image: ${{ matrix.job.container-image }}
          enable_arm64:  ${{ matrix.job.enable_arm64 }}
